### ISSUE TITLE
'RangeIndex' error while using weighted median

### ISSUE THREAD

**Issue by SimaSoltani** [tinybike/weightedstats#3]
Hi,

I have a test sample as follow:
**df  = pd.DataFrame([['Alabama',4779736,5.7],
		    ['Alaska',710231,5.6],
		    ['Arizona',6392017,4.7],
		    ['Arkansas',2915918,5.6],
		    ['California',37253956,4.4],
		    ['Colorado',5029196,2.8],
		    ['Connecticut',3574097,2.4],
		    ['Delware',897934,5.8]],columns=['State','Population','Murder rate'])**

I tried to use the weighted_median as:
**import weightedstats as ws
ws.weighted_median(df['Murder rate'],weights=df['Population'])**

but the following error showed up on the rerun part of the function(**return data[weights.index(max(weights))]**) :
**TypeError: 'RangeIndex' object is not callable**

It works with the weighted_mean
Thanks
Sima

**Comment by tinybike** [comment]
Hi Sima, I haven't tested this with pandas before, but, a quick fix should be to use `numpy_weighted_median` instead of `weighted_median`:
```python
ws.numpy_weighted_median(df['Murder rate'], weights=df['Population'])                                                                                                                                                                                                                                                                                             
```
The underlying issue is that `weighted_median` expects its inputs to be lists.  So, you can use `weighted_median` if you convert your data and weights to lists first:
```python
ws.weighted_median(list(df['Murder rate']), weights=list(df['Population']))
```
